### PR TITLE
Merge upstream

### PR DESCRIPTION
**Pull request by DaikiMaekawa**

### CODE REVIEW

**Comment by DaikiMaekawa** [comment]
@at-wat PTAL

**Review by at-wat — APPROVED** [review]
LGTM
Please merge it by `Create a merge commit`.

**Comment by at-wat** [comment]
@DaikiMaekawa using squash merge is not good for this PR.

**Comment by DaikiMaekawa** [comment]
@at-wat Should I revert it back?

**Comment by at-wat** [comment]
I'll force push to fix it.

**Comment by at-wat** [comment]
fixed by https://github.com/alpine-ros/rosdistro/pull/60

**Pull request merged**
